site_name: Steves Docs
site_description: Steves Amazing Docs
site_url: https://stevejr.com
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/stevejr/test2
copyright: Copyright &copy; 2021 <a href="https://mirantis.com/">stevehr</a> - All rights reserved.
edit_uri: ""
nav:
  - Overview: README.md
  - Test1: test1/test1.md
theme:
  name: 'material'
  highlightjs: true
  language: 'en'
