name: Remote Dispatch Action Responder
 
on: [repository_dispatch]
 
jobs:
  verify-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Received Event Information
        run: |
          echo "Event Name from env var: $GITHUB_EVENT_NAME"
          echo "Built in Event Name: '${{ github.event_name }}'"
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Client Payload - Repository: '${{ github.event.client_payload.repository }}', Branch: '${{ github.event.client_payload.branch }}', Tag: '${{ github.event.client_payload.tag }}'"
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Checkout Lens repo
        uses: actions/checkout@v2
        with:
          repository: stevejr/lens
          token: ${{ secrets.ACCESS_TOKEN }}
          path: lens
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install MKDocs Material
        run: pip install mkdocs-material
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate Extensions API Reference using typedocs
        run: |
           cd lens
           yarn install
           yarn typedocs-extensions-api
      - name: Consolidate Docs
        run: |
          mkdir -p ./docs/api/lens/extensions
          cp -pr ./lens/docs/extensions/api/* ./docs/api/lens/extensions
          cp -pr ./lens/docs/extensions/* ./docs/extensions
          rm -fr ./docs/extensions/api ./docs/extensions/typedoc-readme.md.tpl
          ls -R ./docs
      - name: Publish Docs
        run: mkdocs gh-deploy --force
