name: Remote Dispatch Action Responder
 
on: [repository_dispatch]
 
jobs:
  verify-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install MKDocs Material
        run: pip install mkdocs-material
      - name: Received Event Information
        run: |
          echo "Event Name: '${{ GITHUB_EVENT_NAME }}"
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Client Payload - Repository: '${{ github.event.client_payload.repository }}', Branch: '${{ github.event.client_payload.branch }}', Tag: '${{ github.event.client_payload.tag }}'"
      - name: Checkout current repo
        uses: actions/checkout@v2
      # - name: Checkout test1 repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{ github.event.client_payload.repository }}
      #     token: ${{ secrets.ACCESS_TOKEN }}
      #     path: test1
      - name: Checkout Lens repo
        uses: actions/checkout@v2
        with:
          repository: stevejr/lens
          token: ${{ secrets.ACCESS_TOKEN }}
          path: lens
          fetch-depth: 0
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate Extensions API Reference using typedocs
        run: |
           cd lens
           yarn install
           yarn typedocs-extensions-api
      - name: Consolidate Docs
        run: |
          mkdir -p ./docs/api/lens/extensions
          cp -pr ./lens/docs/extensions/api/* ./docs/api/lens/extensions
          ls -R ./docs
      - name: Publish Docs
        run: mkdocs gh-deploy --force
#       - name: PONG - Dispatch response to received PING
#         if: github.event.action == 'ping'
#         run: |
#           curl -X POST https://api.github.com/repos/marcnuri-demo/actions-remote-dispatch-a/dispatches \
#           -H 'Accept: application/vnd.github.everest-preview+json' \
#           -u ${{ secrets.ACCESS_TOKEN }} \
#           --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
